version: "3"

services:
  nginx:
    container_name: clinica6mayo_nginx
    image: nginx:alpine
    depends_on:
      - django
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./sockets:/tmp/docker
    ports:
      - "8080:80"

  django:
    build:
      context: .
    container_name: ficha_medica
    image: ficha_django
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DEBUG=True
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    command: uvicorn --reload fichaMedica.asgi:application --host 0.0.0.0 --log-level debug --use-colors --loop uvloop
    healthcheck:
      test: curl -f http://localhost:8000/api/docs/ || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    networks:
      - djangonetwork

  redis:
    image: redis:5.0-alpine
    container_name: ficha_redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - djangonetwork

  db:
    image: postgres:13-alpine
    container_name: ficha_bd
    restart: always
    env_file:
      - .env
    volumes:
      - ficha-db-data:/var/lib/postgresql/data
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=root
#    healthcheck:
#      test: ["CMD", "pg_isready"]
#      interval: 1s
#      timeout: 3s
#      retries: 30
    ports:
      - "5433:5432"


  aprrka:
    restart: always
    build: .
    depends_on:
      - db

  web:
    build: .
    depends_on:
      - db
    links:
      - db:db
    networks:
      - djangonetwork

  postgres:
    container_name: clinica6mayo_postgres
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    ports:
      - "5433:5432"
    volumes:
      - clinica6mayo_pgdata:/var/lib/postgresql/data
      - ./sockets:/var/run/postgresq
    hostname: clinica6mayo_postgres

  pgadmin:
    container_name: clinica6mayo_pgadmin
    image: dpage/pgadmin4:7.0
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - PGADMIN_DISABLE_POSTFIX=true
      - PGADMIN_LISTEN_ADDRESS=0.0.0.0
      - GUNICORN_THREADS=1
    ports:
      - "8081:80"
    depends_on:
      - postgres
    volumes:
      - clinica_pgadmindata:/var/lib/pgadmin

volumes:
  clinica6mayo_pgdata:
  clinica6mayo_pgadmindata:

networks:
  djangonetwork:
    driver: bridge
