# Generated by Django 4.0.3 on 2023-05-24 20:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ci', models.IntegerField()),
                ('genero', models.CharField(choices=[('Masculino', 'M'), ('Femenino', 'F')], max_length=10)),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=8)),
                ('signo_sangre', models.CharField(blank=True, choices=[('POSTIVO', '+'), ('NEGATIVO', '-')], help_text='Tipo de sangre ej: A+, AB-', max_length=8, verbose_name='')),
                ('numero_seguro', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, max_length=500)),
                ('hipertension_arterial', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
        migrations.CreateModel(
            name='seguro_medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_seguro', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Seguro Medico',
                'verbose_name_plural': 'Seguros Medicos',
            },
        ),
        migrations.CreateModel(
            name='triaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('frecuencia_cardiaca', models.FloatField(blank=True, default=0, null=True)),
                ('frecuencia_respiratoria', models.FloatField(blank=True, default=0, null=True)),
                ('saturacion', models.FloatField(blank=True, default=0, null=True)),
                ('fecha_consulta', models.DateField(default=django.utils.timezone.now)),
                ('temperatura', models.IntegerField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='PacienteTriaje', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Triajes',
                'verbose_name_plural': 'Triajes',
            },
        ),
        migrations.AddField(
            model_name='paciente',
            name='seguro',
            field=models.ForeignKey(blank=True, help_text='Seguro Medico', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seguro_Medico', to='pacientes.seguro_medico'),
        ),
        migrations.CreateModel(
            name='imagenEstudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='estudios/')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='historial_paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True, editable=False)),
                ('fecha_consulta', models.DateField(default=django.utils.timezone.now)),
                ('peso', models.IntegerField(blank=True, null=True)),
                ('indice_masa', models.FloatField(blank=True, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('motivo_consulta', models.CharField(blank=True, max_length=500)),
                ('sintomas', models.CharField(blank=True, max_length=500)),
                ('diagnostico', models.CharField(blank=True, max_length=500)),
                ('tratamiento', models.CharField(blank=True, max_length=500)),
                ('app', models.CharField(blank=True, max_length=500)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Paciente', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Historial Del Paciente',
                'verbose_name_plural': 'Historial del Paciente',
            },
        ),
    ]
