# Generated by Django 4.0.3 on 2022-07-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='seguro_medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_seguro', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Seguro Medico',
                'verbose_name_plural': 'Seguros Medicos',
            },
        ),
        migrations.CreateModel(
            name='paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ci', models.IntegerField()),
                ('genero', models.CharField(choices=[('Masculino', 'M'), ('Femenino', 'F')], max_length=10)),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=8)),
                ('signo_sangre', models.CharField(blank=True, choices=[('POSTIVO', '+'), ('NEGATIVO', '-')], max_length=8)),
                ('numero_seguro', models.IntegerField(blank=True)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('telefono', models.IntegerField(blank=True)),
                ('notas', models.CharField(blank=True, max_length=500)),
                ('seguro', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Seguro_Medico', to='pacientes.seguro_medico')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
            },
        ),
    ]
