# Generated by Django 4.0.3 on 2023-05-26 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenestudios',
            options={'verbose_name': 'Estudio', 'verbose_name_plural': 'Estudios'},
        ),
    ]
